sumpfork/dominiontabs

dominion_tabs.py

Three new options:
* --no-tab-artwork: omits background banner images on tabs
* --no-card-rules: omits card rules from divider body
* --use-text-set-icon: uses text instead of icons to identify/represent the set.

Adding three options to simplify tab output

---

card_db/en_us/card_groups.txt
card_db/en_us/cards.yaml
card_db/en_us/dominion_cards.txt
dominion_tabs.py

Hi,
I've added some options to make it work a bit better to how i want my tabs setup (all configurable)
* remove the sets text at the bottom of the page
* remove the individual tabs for prizes, shelters, travellers, etc
* remove the back page

Add some grouping and cleanup options

---

card_db/en_us/cards.yaml
card_db/en_us/dominion_cards.txt
dominion_tabs.py

Issue #13: Page and Peasant Cost
Fixed costs to add * and + where necessary. Modified regex to allow 
cost to end in * or +. Adventures cards missing from yaml version so
you'll need to keep this in mind when those are added.
Tested against both yaml and non-yaml card databases.

Issue 13 - Updated costs with * and +

---

dominion_tabs.py

Added 3 enhancements:
--fulltab to make the tab the full width of the divider
--center_name to center the card name on the tab
--back_offset_height to add points in the vertical direction on the back
page

Enhancements - fulltab, center_name, back_offset_height

---

dominion_tabs.py

I made the smallest number of changes to make this work.
Basically, font.face.descent has a negative value.  So in order to get the full font height, the absolute value must be used.  That corrected getting the correct font size selected.
The second fix had the footer printed vertically in the middle of the space between the last card and the margin.  But all the calcuations on font size assumed the full space could be used.  So moved the printing of the footer to the very bottom at the margin.
That said, I'm not sure the function drawSetNames is really doing everything right.  
Not sure if the other layout is ever used.  And the use of layout[] outside the "for layout in layouts:" loop is odd.  I think this whole thing could use some clean up.

Fix for Issue #20 - Unsleeved horizontal A4 sheets overlap with expansion name

---

card_db/en_us/card_groups.json
card_db/en_us/cards.json
domdiv/cards.py

I've added some initial support for Empires: I've added the cards with their cost, name, and type. I added a description for some before I ran out of time. No artwork. No support for debt. I only use text on my dividers and only put the name of the card and its expansion. Hope this gets you started.
Also, fixed a bug with the --use-text-set-icon parameter.

Initial support for Empires

---

card_db/de/cards.json
card_db/de/mapping.json
domdiv/cards.py

This is based on #74 but adds the mapping for the promo card names and fixes some of the logic surrounding missing card set images.

German promo cards

---

card_db/de/card_groups.json
card_db/en_us/card_groups.json
card_db/fr/card_groups.json
card_db/it/card_groups.json

Fixed "Settlers / Bustling Village" group per #81 as it was backward causing it not to match cards.json.  
As I checked for the same problem in the other translations, I found that they weren't translations but just copies of a card_groups.json from before 7355c8f6 .  I have copied the updates from that sha into the other three card_groups.json with the fix for Settlers / Bustling Village.  
This means more entries needing translation, but if the code tries to use the translations at least they are complete.

Fixed "Settlers / Bustling Village" per #81

---

card_db/sets_db.json
domdiv/__init__.py
domdiv/cards.py
domdiv/draw.py

This assumes the following file structure:
```
card_db/
cards_db.json
sets_db.json
<language>/
cards_text.json
sets_text.json
```
Files that are needed are:
- cards_db.json
- cards_text.json and sets_text.json for each supported language
**Other changes:**
Added option called `--edition` that can be "1", "2", "latest", or "all". Defaults to "all".
This allows for a quick filtering for those that don't want everything (i.e., "all").
- "1" is for all 1st editions of expansions. It also includes 2nd edition update packs.
- "2" is for all 2nd editions of expansions. So base, Dominion 2nd ed., and Intrigue 2nd ed. (no update packs, since already in 2nd edition)
- "latest" is for base, Dominion 2nd ed., and Intrigue 2nd ed., and all the remaining 1st editions.
Cards can be grouped 3 ways:
- No …

Initial code refactoring for card db change

---

card_db/cards_db.json
card_db/en_us/cards_en_us.json

Trash card [became a mat in 2nd edition](http://wiki.dominionstrategy.com/index.php/Trash)
Replaced unneeded unicode chars for simplicity
Replaced HTML `<br>` with `\n` and tightened spacing

Remove Trash Card from 2nd edition, replace HTML line breaks & unicode

---

card_db/sets_db.json
domdiv/__init__.py
domdiv/draw.py

Fixed a number of small things:
- The extra expansion dividers really don't have randomizers.  So there should not be a "count".
- The Events and Landmarks at the global level are no longer printing a set icon.
- Removed a debug statement
- Fixed so Expansion dividers do not go through the inline graphics and text replacement.  In some cases it was replacing parts of card names with graphics (e.g., Potion)
- added "_ Coin" to print empty coin.

wvoigt small fixes

---

domdiv/draw.py

When no text was on the front of a wrapper, the back wrapper text and tab were not in the proper location.
This was due to exiting the routine without doing the self.canvas.restoreState().
Cleaned up the code to be easier to read and to exit cleanly.

Fix issue #145 when no text on front of a wrapper

---

domdiv/draw.py

This mostly fixes Issue #155.  This seems to occur only with the VP image.  I've seen several coin and potion, and debt images at the end of a line and they are justified correctly.  There is some strange interaction with the VP image and the paragraph wrap function in reportlab.
While not completely fixing the image out of the normal paragraph boundary, at least this keeps it within the margins of the card.

Fix Prosperity rules text running over

---

domdiv/main.py

This updates/fixes the existing preview code that generates a png image of the first page of the dividers.
It also adds two new command line options, `--preview` to use the code above to write a preview image instead of generating the whole pdf divider set, and `--preview_resolution` to set the DPI of the generated preview images.

Preview option

---

domdiv/main.py

Fix for issue #168 (incorrect sorting for French card names with accents)
I used this technique which seems to be the best one without adding a new library dependency :
https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string/518232#518232

fix for correctly sorting card names with accents

---

domdiv/card_db/cards_db.json

From BGG user Aziden:
`The count for Platinum (in Base/Prosperity) is incorrect. There are 12 Platinum, not 10.`

correct the count of Platinum cards

---

domdiv/main.py

Fix issue recorded at sumpfork/bgtools_web#11
This is a more simple fix than the one proposed in Pull Request #181.
A few things to note:
1. As it is right now, per line 964 of main.py
```
if options.base_cards_with_expansion:
cards = [card for card in cards if card.cardset_tag.lower() != 'base']
else:
cards = [card for card in cards
if not cardSorter.isBaseExpansionCard(card)]
```
If you want the base cards with the expansion, it will not print the base cards separately.  That may not be intuitive via the web interface.
2, As it is right now, when included in an expansion, the base cards are sorted to the end.

Fix for base cards printing with expansions

---

domdiv/main.py
domdiv/tests/text_tab_tests.py

Some of the arguments used hyphens/dashes `-` and some use underscores `_`. I think that they should at least be consistent. [GNU](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html) recommends using hyphens/dashes.
This is a breaking change.

standardize arguments to use hyphens

---

.travis.yml
domdiv/tests/carddb_tests.py
domdiv/tests/codestyle_tests.py
domdiv/tests/layout_tests.py
domdiv/tests/text_tab_tests.py
setup.py
tools/update_language.py

This is a minimal integration of @wvoigt's language fix up tool into the unit tests. Mainly makes sure that if we run the language tool and diff the output to what's checked into the `domdiv` package there are no important differences - especially, nothing got reverted to English because the 'untranslated' field was not updated. This is the main mistake I've seen from helpful contributions providing translations.
This PR also
- minimally turns the language tool into a more easily runnable script by taking arguments and not assuming that it's run from a specific directory
- switches testing to py.test - it seems to be the thing nowadays, and I have more experience with it than other frameworks

Test language tool run

---

domdiv/draw.py
domdiv/main.py

This is an attempt at Issue #120.
This adds options --info and -info-all:
--info to add a page that has all the options used for the PDF file.
--info-all is the same as --info, but includes pages with all the possible options that can be used.

Add option to add pdf page with option information

---

domdiv/card_db/nl_du/cards_nl_du.json

The Dutch translation of the name of the Adventurer card was incorrect. This commit fixes that translation.
Source: http://wiki.dominionstrategy.com/index.php/Adventurer

Fix Dutch Adventurer translation

---

domdiv/card_db/cards_db.json
domdiv/card_db/cz/cards_cz.json
domdiv/card_db/cz/types_cz.json
domdiv/card_db/de/cards_de.json
domdiv/card_db/de/types_de.json
domdiv/card_db/en_us/cards_en_us.json
domdiv/card_db/en_us/types_en_us.json
domdiv/card_db/fr/cards_fr.json
domdiv/card_db/fr/types_fr.json
domdiv/card_db/it/cards_it.json
domdiv/card_db/it/types_it.json
domdiv/card_db/nl_du/cards_nl_du.json
domdiv/card_db/nl_du/types_nl_du.json
domdiv/card_db/sets_db.json
domdiv/card_db/types_db.json
domdiv/card_db/xx/cards_xx.json
domdiv/card_db/xx/types_xx.json
domdiv/cards.py
domdiv/main.py
domdiv/tests/carddb_tests.py

This provides the features requested in Issue #175
It relies on changes made for the randomizer card output on the expansion dividers (Pull #196 )
This is a cleaner version of Pull #197.

Additional Divider Options: Curse, Trash, Start Decks - 2nd attempt

---

domdiv/card_db/cards_db.json

As the start deck will always be there, IMHO it should not be included in a randomizer (there is no Start Deck randomizer card in Dominion sets).

exclude start deck from randomizer

---

domdiv/draw.py

The first patch fixes `--info` output, which was missing a `</para>` tag.
The second patch fixes output using Python 2.x, where the `MULTIPLICATION SIGN` character was rendered as `\u00d7` when outputting card counts.

A couple of minor fixes

---

domdiv/main.py
domdiv/tests/carddb_tests.py
tools/update_language.py

Inspired by Issue #240  I think this solves that issue as well as provides some added function.
This adds two new options that limit/reduce the number of dividers to the matching type(s) given. This would happen after any other options are used to select expansions, group cards, etc. Basically this is done right before the dividers are sorted just before they are printed.
* `--only-type-any,` alias `--type-any`, alias `--only-type`
keeps any dividers that have _any_ of specified types
* `--only-type-all`, alias `--type-all`
keeps any dividers that match _all_ of the specified types
For example:
`--only-type-any project expansion` would include in the output only expansion and project dividers
`--only-type-all duration attack` would include in the output only dividers that had both …

Add only-type-any and only-type-all options

---

src/domdiv/main.py
tests/layout_tests.py

previously, if you used, ie, "--cost=body-top", the cost would show in
the tab AND body-top.  Since the help text implies that the way to
accomplish this should be "--cost=tab --cost=body-top" (and because if you
put it in body-top, it's probably because you want to save space on the
tab)

allow cost / set-icon to be displayed in body-top ONLY

---

src/domdiv/main.py
tests/carddb_tests.py

provides an easy way to include nearly all expansions, except for a select few
In my case, I noticed that you changed "--base-cards-with-expansion" so it doesn't exclude the "base" expansion automatically, and I wanted a way to do that. Adding a new option seemed like a more generally useful way to go about it!
Also adds tests, both for this, and the "normal" --expansion option
Thanks again for the great tool!

add --exclude-expansion option (and test)

---

src/domdiv/draw.py

So, I encountered a situation where when I used `--back_offset_height -10`, the setName text was intruding into the divider back.
Apparently the code for printing the dividers doesn't take the back offset settings into account, so I fixed it so that it at least uses it in it's calculations for the available space.
This made the location alternate between bottom (for front) and left (for back), which felt a bit odd, so I also made the code just place the setNames on whichever side has the most space, which is probably a good idea in general.
The commit breakdown is:
- The first two commits (46450c923b2d1d6c1ff7cf88da8f764998dc970f and d9070a62e57ff4910b29e34ad745141c9f651fcc) clean up and consolidate code (in ways that make subsequent commits easier)
- …

Fix setNames intruding into dividers when back_offset_height given negative value

---

src/domdiv/main.py
tests/carddb_tests.py

Thank you so much for this incredible project!
Here is a bug fix: expansion card didn't sort cards list in the true alphabetical order, like the other part of the code did.
For example, the cards for the french expansion Hinterlands were printed in the correct order (the alternation of left and right tabs were correct), but the expansion summary card did not.
Expected: `[…] 'Complot', 'Développement', 'Duchesse', 'Écuries', 'Mandarin', […]`
Actual: `[…] 'Complot', 'Duchesse', 'Développement', 'Mandarin', […], 'Écuries'`

Fix cards list order for accents in expansion card

---

src/domdiv/draw.py
src/domdiv/main.py

turn down background opacity to help text show up better against dark
backgrounds
this was particularly need on my printer, which I think prints a bit darker than normal

add --tab-artwork-opacity flag

---

src/domdiv/card_db/labels_db.json

I added config for these labels:
https://www.herma.com/office-home/product/tab-labels-a4-superprint-4201/
since they fit perfectly with these dividers:
https://www.bcwsupplies.com/trading-card-dividers-horizontal

feat: added label sheet Herma 4201

---

src/domdiv/draw.py
src/domdiv/main.py

Various changes to fix issues #284 #295 #296.
Added `--full-expansion-dividers` option to force expansion tabs to be full width with centered text.

Fixes for #284 #295 #296 #248

---

src/domdiv/cards.py
src/domdiv/draw.py
src/domdiv/main.py

Added `--use-set-icon` option to force cards with unique icons to instead use their standard set icon.  This really only applies to Promo cards.
This is a fix for Issue #247

Fix for #247 Promo Card Icons

---

card_db_src/en_us/sets_en_us.json
card_db_src/sets_db.json
card_db_src/types_db.json
src/domdiv/card_db/cz/sets_cz.json
src/domdiv/card_db/de/sets_de.json
src/domdiv/card_db/en_us/sets_en_us.json
src/domdiv/card_db/fr/sets_fr.json
src/domdiv/card_db/it/sets_it.json
src/domdiv/card_db/nl_du/sets_nl_du.json
src/domdiv/card_db/sets_db.json
src/domdiv/card_db/types_db.json
src/domdiv/card_db/xx/sets_xx.json
src/domdiv/cards.py
src/domdiv/draw.py
src/domdiv/main.py

I took a look at this yet for issue #166 again with some fresh eyes.  I propose the following changes:
Changes to Options:
* `--group-special`
This is the same as `--special-card-groups` in the past.
* `--group-kingdom`
This will group non-Kingdom (i.e., no randomizer) cards into an Extra section for the Expansion.
This includes moving base cards to the Extra section if `--base-cards-with-expansion` is given.
*`--group-global [Events|Landmarks|Projects|Ways]`
Combines the --exclude-xxx options into a single option that can contain any number of wanted card types to be included in the "Extra" section.
This can be called once with any/all desired types, or called multiple times with one or more types.
`--group-global` with no parameters will use ALL the global groups`.
*QUESTION*: Should …

Fix issue#166

---

src/domdiv/main.py

This corrects issue #322.  Only expansions that have been requested will have their non-randomizer cards placed into an Extra set.
As a minor benefit, it reduces by 1 the number of times all the cards are examined.

Fix for Issue#322

---

card_db_src/en_us/cards_en_us.json
src/domdiv/card_db/cz/cards_cz.json
src/domdiv/card_db/en_us/cards_en_us.json
src/domdiv/card_db/fr/cards_fr.json
src/domdiv/card_db/it/cards_it.json
src/domdiv/card_db/xx/cards_xx.json

Overlord has been missing the `extra` FAQ entry.
This PR is adding 'unofficial FAQ' in lack of official ones.
See http://wiki.dominionstrategy.com/index.php/Overlord

Missing Overlord FAQs

---

src/domdiv/draw.py
src/domdiv/main.py

Adds a new `linetype = line-cropmarks` option, analogous to `dot-cropmarks`, that generates both outlines and cropmarks.
Fixes #362.

Add "linetype = line-cropmarks" option

---

card_db_src/en_us/cards_en_us.json
src/domdiv/card_db/cz/cards_cz.json
src/domdiv/card_db/de/cards_de.json
src/domdiv/card_db/en_us/cards_en_us.json
src/domdiv/card_db/fr/cards_fr.json
src/domdiv/card_db/it/cards_it.json
src/domdiv/card_db/nl_du/cards_nl_du.json
src/domdiv/card_db/xx/cards_xx.json

This commit fixes the typos mentioned in  https://github.com/sumpfork/dominiontabs/issues/352#issuecomment-1089483299

Fix card name typos mentioned in #352.

---

card_db_src/cards_db.json
card_db_src/en_us/cards_en_us.json
src/domdiv/card_db/cards_db.json
src/domdiv/card_db/cz/cards_cz.json
src/domdiv/card_db/de/cards_de.json
src/domdiv/card_db/en_us/cards_en_us.json
src/domdiv/card_db/fr/cards_fr.json
src/domdiv/card_db/it/cards_it.json
src/domdiv/card_db/nl_du/cards_nl_du.json
src/domdiv/card_db/xx/cards_xx.json

First pass at adding "extra" fields for Allies dividers.  I had to do some cleanup regarding the split piles randomizers, choosing to index by capitalized name for consistency with the grouping tags.  Not doing that led to errors from update_languages.

Add FAQ sections for Allies dividers.

---

src/domdiv/main.py

Should resolve Issue #347 
Lines in the file specified by --cardlist can now either include a card or exclude a card.
Include works as before.  Optionally, you can now add a '+' at the start of a line.
To exclude a card, just preface the line with a '-' (minus).
There can be white space before and spaces/tabs after the + or -

Change --cardlist to also allow excluding cards

---

.github/workflows/lint_and_test.yml
tox.ini

Add other platforms to test on in github actions as we've had trouble with differing behaviours.

Add other platforms to run tests on

---

.dockerignore
README.md
dockerfile

This adds a `dockerfile` that can be built more easily and platform-agnostic than the Python virtual env and some instructions for how to run that via CLI. This was based on my own suggested in [another PR](https://github.com/sumpfork/dominiontabs/pull/499#issuecomment-1954833806).
@sumpfork LMK if you have questions, otherwise go ahead and merge this.
Potential next steps:
1. Build the dockerfile via GitHub Workflows and host a pre-built one in this project
2. Add additional dockerfile-based testing steps to make testing easier
3. Add instructions to bind mount the project dir to use docker in development iteration loop

Initial Dockerfile

---

dockerfile

- Fix Arch Mismatch [identified here](https://github.com/sumpfork/dominiontabs/pull/499#issuecomment-1960451040)
- Adding `python3-icu` as [discussed here](https://github.com/sumpfork/dominiontabs/pull/499#issuecomment-1960384732)

fix docker arch mismatch problem, add python3-icu

---

src/domdiv/db.py
src/domdiv/draw.py
src/domdiv/main.py
src/domdiv/resource_handling.py

This has come up a couple of times, latest in #544.
pkg_resource from setuptools is deprecated and often not installed (we don't specify it as a runtime dependency anywhere, which is bad.
So, upgrade to use importlib.resources.
Fixes #325.

Remove use of pkg_resources

---

src/domdiv/draw.py

I'm working on several unrelated improvements. I'm going to try to submit them as separate, small PRs, but if @sumpfork would prefer fewer, larger PRs, I'm happy to do that too.
This adds a workaround for the fact that the arrow character isn't present in the various custom fonts used on dominion cards, by always rendering it using Times Bold. I'm removing a different workaround that had instead replaced it with a dash.

Keep arrows in card names for groups, but always render in Times Bold

---

src/domdiv/config_options.py
src/domdiv/main.py

I want to be able to put my events, landmarks, etc at the end of the cards in an expansion, with alternating tabs. This lets me do that. 
I don't fully understand the purpose of the "extras" pseudo-expansions. Maybe they're for this same purpose? If there's another way to accomplish this, I'd be happy to close this PR and instead update the documentation to make it more clear.

Allow sorting non-kingdom cards to the end of the expansion

---

src/domdiv/config_options.py
src/domdiv/db.py
src/domdiv/main.py
tests/__init__.py
tests/selection_tests.py

It seems silly to me that when grouping is turned on, and the promo "expansion" is included, it generates a card called "Events - Promo" with a single card in it (Summon). 
This provides an option to make it not do that. I've also refactored the code that creates the groups to be more explicit about what it's doing. Rather than updating the first card it finds in the group to be the group holder (but also still kind of sometimes retain its original data for purposes like the card count), now I'm explicitly making a new card to be the holder, and tracking a list of the unmodified cards in the group that can be used for other purposes if necessary.

Ungroup cards if the group only has one card in it

---

src/domdiv/cards.py
src/domdiv/db.py
src/domdiv/draw.py
src/domdiv/main.py
tests/selection_tests.py

These are a few minor improvements I made while working on other things that would be nice to merge separately. 
I now understand more about the way the card count was working previously (and I don't particularly like it). Now it's more explicit about what's a list and what's an int, and I have more confidence that the refactor I did to the card grouping code is correct, although the unit test for it is probably enough to show that the previous version was correct too.

Move Card defaults to read time
