- card_db/en_us/dominion_cards.txt
Cards in order as they were printed on the Adventures rule book. May need reordered. Also - the Traveller cards may need some special handling. I haven't looked at the rest of your code.
> Added Adventures Raw Text

- card_db/de/cards.json
Readded all german extra text and added the coin symbol in appropiate places
> Update german basic extra texts (ref #21)

- card_db/de/cards.json
Readded all german extra text and added the coin symbol in appropiate places
> Update german seaside extra text (ref #21)

- card_db/de/cards.json
Add all german extra text and added the coin symbol in appropiate places
> Update and add german adventures cards with extra text (ref #21)

- card_db/en_us/cards.json
As reported here https://github.com/sumpfork/dominiontabs/issues/55
> Remove duplicate Settlers entry

- domdiv/__init__.py
- domdiv/draw.py
These changes address issue #68
> Add option for Center Tab

- card_db/de/cards.json
- card_db/de/mapping.json
I'm not sure about mapping.json, please check it. Thank you!
> Add German Sauna/Avanto promo cards.

- card_db/en_us/cards.json
- tests/carddb_tests.py
Hey sumpfork,
Thanks for the dominiontabs code, I love the wrappers and I'm currently printing and making the wrappers as I incorporate Empires and my update pack.  (migrating away from tabs only as my fat fingers have trouble extracting the cards from my vertical organizer slots).
This pull request is for adding the 7 cards added in the update pack to the english card_db.  I don't know other languages to help with those.
According to wiki.dominionstrategy.com these are in the base set, so I included them as 'dominion' cards.
> added update cards to the dominion set (english only)

- tools/CrossReference.csv
Please add this for Czech card names :)
> Adding Czech language

- domdiv/card_db/cards_db.json
- domdiv/card_db/cz/cards_cz.json
- domdiv/card_db/de/cards_de.json
- domdiv/card_db/en_us/cards_en_us.json
- domdiv/card_db/fr/cards_fr.json
- domdiv/card_db/it/cards_it.json
- domdiv/card_db/nl_du/cards_nl_du.json
- domdiv/card_db/xx/cards_xx.json
> Remove Leprechaun - Wish grouping

- domdiv/card_db/de/cards_de.json
Hello! I translated the 2nd Edition Base and Intrigue cards for the german edition. Hopefully everything went well, since I'm not experienced in programming or GitHub at all! I imitated the previous (english) writing though.
Best regards!
> 2nd Edition Base and Intrigue translated

- domdiv/main.py
One more - this makes it work under python 3.5 (higher versions auto-decode these inside the json package.)
> decode files as utf-8 on load

- domdiv/draw.py
- tools/update_language.py
> Fix for tab left-align issue

- card_db_src/nl_du/cards_nl_du.json
- src/domdiv/card_db/nl_du/cards_nl_du.json
See #287, just transferring things due to new card db setup.
> replacement for PR #287

- card_db_src/fr/cards_fr.json
- src/domdiv/card_db/fr/cards_fr.json
This replaces #281 after db changes.
> replacement for PR 281

- card_db_src/de/cards_de.json
- src/domdiv/card_db/de/cards_de.json
This replace #278 after card db changes.
> replacement for PR #278

- card_db_src/cards_db.json
- card_db_src/en_us/cards_en_us.json
- src/domdiv/card_db/cards_db.json
- src/domdiv/card_db/cz/cards_cz.json
- src/domdiv/card_db/de/cards_de.json
- src/domdiv/card_db/en_us/cards_en_us.json
- src/domdiv/card_db/fr/cards_fr.json
- src/domdiv/card_db/it/cards_it.json
- src/domdiv/card_db/nl_du/cards_nl_du.json
- src/domdiv/card_db/xx/cards_xx.json
Starting pull request for issue #312 
Can add any others that might show up.
> Menagerie Issues

- .github/workflows/compile_card_db.yml
- .github/workflows/lint_and_test.yml
- .github/workflows/publish.yml
- .travis.yml
- card_db_src/en_us/sets_en_us.json
Move travis setup to githubs actions for
- linting/testing
- publishing to pypi (untested until I make a release)
- compiling the card db
> GitHub actions

- card_db_src/fr/cards_fr.json
- src/domdiv/card_db/fr/cards_fr.json
Hi, I added the French translations for the 7 new cards of Dominion 2nd edition.
> Add French translations for Dominion 2nd Edition (Base Set)

- card_db_src/it/cards_it.json
- card_db_src/translation.md
- src/domdiv/card_db/it/cards_it.json
- src/domdiv/card_db/translation.md
- src/domdiv/tools/update_language.py
> Italian Dark Ages and Adventures

- card_db_src/cards_db.json
- card_db_src/cz/cards_cz.json
- card_db_src/de/cards_de.json
- card_db_src/en_us/cards_en_us.json
- card_db_src/fr/cards_fr.json
- card_db_src/it/cards_it.json
- card_db_src/nl_du/cards_nl_du.json
- card_db_src/xx/cards_xx.json
- src/domdiv/card_db/cards_db.json
- src/domdiv/card_db/cz/cards_cz.json
- src/domdiv/card_db/de/cards_de.json
- src/domdiv/card_db/en_us/cards_en_us.json
- src/domdiv/card_db/fr/cards_fr.json
- src/domdiv/card_db/it/cards_it.json
- src/domdiv/card_db/nl_du/cards_nl_du.json
- src/domdiv/card_db/xx/cards_xx.json
Just did a simple find/replace which I think should work!
Fix for https://github.com/sumpfork/dominiontabs/issues/335
> Fix The River's Gift. to The River's Gift

- card_db_src/nl_du/cards_nl_du.json
- src/domdiv/card_db/nl_du/cards_nl_du.json
> Fix "9indien" stray nine in Dutch translation

- card_db_src/en_us/cards_en_us.json
- card_db_src/types_db.json
- src/domdiv/card_db/cz/cards_cz.json
- src/domdiv/card_db/de/cards_de.json
- src/domdiv/card_db/en_us/cards_en_us.json
- src/domdiv/card_db/fr/cards_fr.json
- src/domdiv/card_db/it/cards_it.json
- src/domdiv/card_db/nl_du/cards_nl_du.json
- src/domdiv/card_db/types_db.json
- src/domdiv/card_db/xx/cards_xx.json
Descriptions were copied from Dominion Strategy wiki
> Add descriptions for Allies cards

- src/domdiv/main.py
> Remove unused --write-json option

- setup.cfg
- src/domdiv/draw.py
- src/domdiv/main.py
> Add --tab-artwork-resolution option to limit DPI.

- .github/workflows/compile_card_db.yml
- .github/workflows/lint_and_test.yml
- .github/workflows/make_card_db_pr.yml
- card_db_src/en_us/cards_en_us.json
See if I can 
1) make the PR created if someone makes a PR without updating languages reference the original PR (complicated, it turns out)
2) have the new PR comment on the old one.
> Improve auto-PR functionality

- pyproject.toml
- src/domdiv/cards.py
- src/domdiv/draw.py
- src/domdiv/fonts/README.md
- src/domdiv/main.py
Use loguru for logging. Turn down log level by default but add option to set it.
Clean up font use in the non-latin1 case.
@smrky1
> Improve logging; simplify font handling

- src/domdiv/config_options.py
- src/domdiv/draw.py
- src/domdiv/main.py
- src/domdiv/tools/common.py
- tests/carddb_tests.py
- tests/generation_tests.py
Clean up some unnecessarily complicated expressions, make most format()s f-strings
> Cleanup, f-strings

- tests/carddb_tests.py
With and without grouping, and also the total number of cards.
> Add test to assert the number of cards in each set
